awslabs/aws-crt-nodejs

package-lock.json
package.json
scripts/deps_build.ts
tsconfig.json

package.json & tsconfig.json improvements

---

binding.gyp
lib/native/http.ts
lib/native/io.ts
source/http_connection.c
source/io.c
source/io.h
source/module.c
source/module.h
source/mqtt_client_connection.c
test/http.ts

Generalized dispatching node callbacks

---

jest.config.js
lib/browser.ts
lib/browser/error.ts
lib/index.ts
lib/native/binding.ts
lib/native/error.ts
lib/native/http.ts
lib/native/io.ts
package.json
scripts/deps_build.ts
source/http_connection.c
source/module.c
test/http.ts

HTTP Bindings

---

lib/common/http.ts
lib/index.ts
lib/native/binding.ts
lib/native/http.ts
lib/native/io.ts
package-lock.json
samples/node/elasticurl/elasticurl.ts
samples/node/elasticurl/package-lock.json
samples/node/elasticurl/package.json
samples/node/elasticurl/tsconfig.json
source/http_connection.c
source/http_stream.c
source/http_stream.h
source/io.c
source/io.h
source/module.c
test/http.ts

HTTP Streams

---

lib/common/http.ts
lib/native/http.ts
samples/node/elasticurl/elasticurl.ts

PR Feedback from previous HTTP PR

---

lib/common/event.ts
lib/native/http.ts
lib/native/native_resource.ts
samples/node/elasticurl/elasticurl.ts

Switched HttpStreams to be node-style streams

---

lib/browser.ts
lib/browser/http.ts
lib/browser/io.ts
lib/native/http.ts
package-lock.json
package.json
samples/browser/http/index.html
samples/browser/http/index.ts
samples/browser/http/package-lock.json
samples/browser/http/package.json
samples/browser/http/tsconfig.json
samples/browser/http/webpack.config.js
source/http_connection.c
test/http.ts

Added browser HTTP, converted node HTTP to use event streams, updated tests

---

lib/browser/error.ts
lib/native/aws_iot.ts
lib/native/error.ts
lib/native/io.ts
source/io.c
source/io.h
source/module.c
test/io.ts

Renames and clean up from previous PRs

---

lib/browser/aws_iot.ts
lib/browser/mqtt.ts
lib/common/mqtt.ts
lib/native/aws_iot.ts
lib/native/mqtt.ts
source/mqtt_client_connection.c
test/mqtt.ts

Added will support, cleaned up params to connect before it killed us all

---

lib/native/http.ts
package-lock.json
package.json
source/http_connection.c
source/http_connection.h
source/http_connection_manager.c
source/http_connection_manager.h
source/io.c
source/io.h
source/module.c
source/mqtt_client.c
source/mqtt_client_connection.c
test/http.ts

Added http_connection_manager binding

---

lib/browser/http.ts
lib/native/http.ts
package-lock.json
package.json
samples/browser/http/index.ts
samples/browser/http/package-lock.json
test/http.ts
test/mqtt.ts

HTTP connection manager for browser

---

.gitmodules

Now that my PR is merged and my fork is gone...

Update cmake-js submodule to point at the upstream

---

.gitmodules
lib/browser/aws_iot.ts
lib/browser/io.ts
lib/browser/mqtt.ts
lib/common/io.ts
lib/native/aws_iot.ts
lib/native/io.ts
lib/native/mqtt.ts
package-lock.json
package.json
source/mqtt_client_connection.c
test/mqtt.ts

Implement MQTT client in terms of socket_options

---

lib/native/http.ts
lib/native/io.ts
source/http_connection.c
source/http_connection_manager.c
source/io.c
source/io.h
source/logger.c
source/module.c
test/http.ts

Added TlsConnectionOptions, updated APIs/tests to use them

---

source/io.c
source/logger.c
source/module.c

~~`(const char *)aws_string_bytes(some_string)`~~
~~`(const char *)some_string->bytes`~~
`aws_string_c_str(some_string)`

aws_string_c_str()

---

lib/browser/http.ts
lib/common/http.ts
lib/native/http.ts
lib/native/mqtt.ts
source/http_connection.c
source/http_connection.h
source/http_connection_manager.c
source/logger.c
source/module.c
source/mqtt_client_connection.c

Websockets & Proxies

---

jest.config.js
lib/common/http.ts
lib/native/binding.d.ts
lib/native/binding.js
lib/native/crypto.ts
lib/native/error.ts
lib/native/http.ts
lib/native/io.ts
lib/native/mqtt.ts
package-lock.json
package.json
test/tsconfig.json
tsconfig.base.json
tsconfig.json

Implement binding.ts declaration file

---

lib/browser/mqtt.ts
lib/native/binding.d.ts
lib/native/mqtt.ts
source/module.c
source/mqtt_client_connection.c
source/mqtt_client_connection.h
test/mqtt.ts

Unsolicited Publish bindings

---

builder.json
lib/browser/mqtt.ts
lib/native/binding.d.ts
lib/native/mqtt.ts
source/mqtt_client_connection.c
test/crt.ts
test/mqtt.ts

https://github.com/awslabs/aws-crt-nodejs/pull/47

Ergonomic API improvements from subscribe_to_any PR

---

CMakeLists.txt
builder.json
lib/native/binding.d.ts
lib/native/mqtt.ts
package-lock.json
package.json
source/module.c
source/mqtt_client_connection.c
source/mqtt_client_connection.h
test/mqtt.ts

subscribe_to_any -> on_message

---

.github/workflows/mac-osx-ci.yml
builder.json
source/module.c
test/mqtt.ts

Use github actions for OSX

---

lib/native/binding.js
package.json
scripts/build.js
scripts/install.js
scripts/tsc.js
tsconfig.base.json

Turns out I was wrong, luckily all I hurt was myself.

Fix incorrect implementation of binding.d.ts

---

README.md
lib/native/binding.js
package-lock.json
package.json
samples/browser/http/package-lock.json
samples/browser/http/package.json
samples/browser/pub_sub/package-lock.json
samples/browser/pub_sub/package.json
samples/node/elasticurl/elasticurl.ts
samples/node/elasticurl/package-lock.json
samples/node/elasticurl/package.json

NPM upgrade, set version to 1.0.0

---

package-lock.json
package.json
samples/browser/http/package-lock.json
samples/browser/pub_sub/package-lock.json
source/io.c

Updated aws-common-runtime deps to latest releases, security fixes

---

package.json
source/io.c

Windows fixes

---

README.md
builder.json
package.json

Updated readme, fixed description in package.json

---

lib/browser/mqtt.ts
package-lock.json
package.json

Additionally updated dependencies via npm audit fix/npm update

Use configured values for keepalive, timeout, fixed default keepalive

---

package-lock.json
package.json
scripts/install.js

Do not depend on cmake-js at runtime/install time unless developing

---

package-lock.json
package.json

Update some insecure dependencies

Update dependency tree

---

package-lock.json
samples/browser/http/package-lock.json
samples/browser/http/package.json
samples/browser/pub_sub/package-lock.json
samples/browser/pub_sub/package.json

Updated webpack>minimist|kind-of for security vulnerabilities

---

package.json

Updated to v1.1.3

---

package-lock.json
samples/browser/http/package.json
samples/browser/pub_sub/package.json

Version bumps

---

continuous-delivery/pack.yml
package.json

Always set the package version to match the git tag when publishing

---

continuous-delivery/pack.yml
continuous-delivery/update-version.sh

Fixed order of operations on updating version

---

package-lock.json
samples/browser/http/package-lock.json
samples/browser/pub_sub/package-lock.json

Updated vulnerable deps via npm audit

---

package.json

*Issue #, if available:* https://github.com/aws/aws-iot-device-sdk-js-v2/issues/18

Added types to package.json to publish TS types

---

.github/workflows/ci.yml
lib/browser/aws_iot.ts
lib/browser/crypto.ts
lib/browser/error.ts
lib/browser/http.ts
lib/browser/io.ts
lib/browser/mqtt.ts
lib/browser/ws.ts
lib/common/crypto.ts
lib/common/event.ts
lib/common/http.ts
lib/common/io.ts
lib/common/mqtt.ts
lib/common/platform.ts
lib/common/resource_safety.ts
lib/index.ts
lib/native/auth.ts
lib/native/aws_iot.ts
lib/native/binding.d.ts
lib/native/crt.ts
lib/native/crypto.ts
lib/native/error.ts
lib/native/http.ts
lib/native/io.ts
lib/native/mqtt.ts
package-lock.json
package.json

Depends on:
* https://github.com/awslabs/aws-crt-builder/pull/43

Doc changes to allow combining CRT docs with IoT Device SDK docs

---

lib/browser/http.ts

Based on feedback from: https://github.com/awslabs/aws-crt-nodejs/pull/92

Browser HTTP fixes

---

lib/browser/http.ts

Cork HttpClientConnection until 'connect' is bound

---

continuous-delivery/build-binaries-linux-x64.yml

Fixed path to binary artifact for linux build

---

docs/globals.html
docs/index.html
docs/modules/aws_crt.html
package-lock.json

* npm audit fix results
* reran doc generation to ensure up to date

Update docs; npm audit fix

---

samples/browser/http/package-lock.json
samples/browser/pub_sub/package-lock.json

Security Updates to dependencies

---

source/mqtt_client_connection.c

https://github.com/aws/aws-iot-device-sdk-js-v2/issues/78
Not really sure it will solve the problem, but this is wrong for sure

interrupt and resume are wrong

---

lib/native/binding.js
package-lock.json

https://github.com/aws/aws-iot-device-sdk-js-v2/issues/86
Upgrade string says 10.13.0, but should say 10.16.0: https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix

Fixing upgrade typo

---

builder.json
scripts/build.js

Enabled tests in CI on windows

---

package-lock.json
source/auth.c

zero out the option

---

package-lock.json
samples/browser/pub_sub/package-lock.json
scripts/build.js
source/module.c

* Switches the nodejs crt to use the dynamically discovered openssl branch of aws-c-cal

Use dynamically bound openssl api discovery

---

.github/workflows/ci.yml
builder.json
package-lock.json
package.json
source/auth.c
source/module.c

Waits for C objects to clean themselves up before proceeding with napi_finalize

Wait for async c objects to clean themselves up

---

.github/workflows/ci.yml

Updating builder for Windows builds

---

.github/workflows/ci.yml
CONTRIBUTING.md
builder.json

find/replace: master->main

---

package-lock.json

* Submodule update to fix aws_mutex_try_lock on Windows

Try lock fix

---

lib/browser/mqtt.ts
lib/common/mqtt.spec.ts

https://github.com/awslabs/aws-crt-nodejs/issues/165
Credit to @edzis who diagnosed the bug and put up PR https://github.com/awslabs/aws-crt-nodejs/issues/171 with the fix. To hasten delivery of this, I made my own branch and PR (It can take a lot of back and forth to get the tests to run when the branch isn't owned by someone in our organization).

Fix browser mqtt.unsubscribe (2)

---

package-lock.json
package.json
test/browser/jest.config.js
test/native/jest.config.js

update dependencies for security

---

source/http_connection.c

proxy option binding

---

.github/workflows/ci.yml
package-lock.json

Updating aws-lc

---

package-lock.json
samples/browser/http/package-lock.json
samples/browser/pub_sub/package-lock.json
samples/node/elasticurl/package-lock.json

npm update to solve the scurity warning

---

samples/browser/http/package-lock.json
samples/browser/pub_sub/package-lock.json

ssri to 8.0.1

---

source/http_connection.c
source/http_connection_manager.c
source/mqtt_client_connection.c

Safe publish

---

source/logger.c
source/mqtt_client_connection.c

Update submodules for proxyv2

---

package-lock.json
package.json
samples/node/elasticurl/package-lock.json

Another way of trying to pin this

---

codebuild/linux-integration-tests.sh
codebuild/linux-integration-tests.yml
package-lock.json
scripts/build.js
scripts/install.js

* Codebuild integration test job
* audit update

Integration test setup

---

lib/native/aws_iot.ts
lib/native/io.ts
lib/native/mqtt.spec.ts
package-lock.json

* Exposing TLS Context Options for builder.
* npm audit fix

Exposing TlsContextOptions for websockets when using AwsIotMqttConnectionConfigBuilder

---

README.md

Build from source instruction

---

package-lock.json
package.json

Update mqtt and crypto

---

package-lock.json
package.json

Cmake revert take2

---

.npmignore
package-lock.json

Update CAL, trim down package

---

.github/workflows/ci.yml
builder.json

Updated CI to use latest builder, node support, and container run scripts

---

package.json
samples/browser/http/package.json
samples/browser/pub_sub/package.json

Depends on:
* https://github.com/awslabs/aws-crt-nodejs/pull/248

Updated dependencies for security fixes

---

continuous-delivery/publish.sh

Forgot to push the local fix to remote

---

scripts/build.js

- rmSync is introduced in v14.14
- rmdirSync Recursive is deprecated :)
- I love JavaScript :)
https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fs_fs_rmdir_path_options_callback

rmSync is introduced in v14.14 :)

---

lib/browser/ws.ts
package-lock.json
package.json

Replace deprecated websocket-stream with ws

---

lib/browser/mqtt.ts

* Clone of https://github.com/awslabs/aws-crt-nodejs/pull/284.  Must be submitted by team member to trigger integration tests.

Browser disconnect

---

package-lock.json
package.json

Update axios, mqtt

---

.github/workflows/ci.yml
.gitmodules
CMakeLists.txt

Fix aws-lc builds.

---

lib/common/http.spec.ts

Tls options leak

---

lib/browser/mqtt.ts
samples/browser/pub_sub/config.ts
samples/browser/pub_sub/index.ts

Turned on reconnecting for browser mqtt connections

Turned on reconnecting for browser mqtt connections

---

continuous-delivery/test-version-exists.sh

Check the version number is not getting smaller before the release got published to npm.

more strict check before release

---

scripts/build.js

Update all submodules, including S2N-TLS and AWS-LC which we hadn't updated for a while due to issues which are now resolved (see https://github.com/awslabs/aws-c-common/pull/925).

 Use latest versions of S2N-TLS and AWS-LC

---

lib/common/mqtt.spec.ts
lib/native/mqtt.spec.ts
test/credentials.ts

Added unit test to setup Mqtt Connect through EC-based certificate and key

---

.github/workflows/ci.yml
builder.json

Setup CI for linux-x86 

---

.github/workflows/ci.yml
codebuild/macos_compatibility_check.py
scripts/build.js

Add compatibility for macos to support 10.9

---

continuous-delivery/build-manylinux2014-aarch64-jenkins.sh

Bad side-effect from MQTT5 merge

Fix CD aarch64 builds

---

lib/browser/aws_iot_mqtt5.ts
lib/browser/mqtt5.ts
lib/native/aws_iot_mqtt5.ts
lib/native/mqtt5.ts

Fix links to the MQTT5 user guide

---

.github/workflows/ci.yml
source/mqtt5_client.c

Added cross-compile win-x86 CI job

---

package-lock.json

bump json5 dep and regenerate package-lock.json to be compatible with lock version 2 (which is backwards compatible with version 1)

bump library versions

---

test/mqtt5.ts

Use a disconnect with a non-zero reason code now that IoT Core supports it

---

builder.json
lib/native/eventstream.spec.ts
lib/native/eventstream.ts
lib/native/eventstream_headers.spec.ts
source/event_stream.c
source/module.c
source/module.h
source/mqtt5_client.c

* Initial message bindings.  Header types will be fully exercised/tested once streams are complete.

Event stream message

---

MQTT5-UserGuide.md

Adjusts MQTT5 userguide to use syntax highlighting, adds a table of contents, and fixes a few minor formatting issues.
________

MQTT5 userguide adjustment

---

package-lock.json

Update y18n version in package-lock.json to avoid vulnerability: https://www.cvedetails.com/cve/CVE-2020-7774/

Fix y18n version in package-lock.json

---

lib/native/io.ts

https://github.com/awslabs/aws-crt-nodejs/issues/429

Remove Buffer constructor invocation

---

continuous-delivery/pack.sh

Bump package size limit

---

continuous-delivery/pack.sh

Source map support added a chunk to the package size

---

lib/browser/aws_iot.ts
lib/native/aws_iot.ts

API Comaptibility

---

.builder/actions/crt_size_check.py
continuous-delivery/pack.sh

Submodule update

---

package-lock.json

bump xml2js version

---

README.md

Updates the README with a link to the node minimum version update discussion.

Node minimum version bump notice

---

source/module.c

Init and clean up aws-c-event-stream

---

.github/workflows/ci.yml

aws-c-auth         v0.7.1 -> v0.7.4
aws-c-cal          v0.6.1 -> v0.6.6
aws-c-common       v0.9.0 -> v0.9.4
aws-c-event-stream v0.3.1 -> v0.3.2
aws-c-http         v0.7.11 -> v0.7.13
aws-c-io           v0.13.29 -> v0.13.35
aws-c-mqtt         v0.9.3 -> v0.9.7
aws-c-sdkutils     v0.1.11 -> v0.1.12
aws-lc             v1.12.1 -> v1.16.0

submodules update -> Fix sigv4 on MacOS 14+

---

source/auth.c
source/http_message.c
source/module.c

Fix signing leaks

---

lib/common/mqtt.spec.ts

Force server to send Will message in Will test

---

.github/workflows/stale_issue.yml

fix stale bot permissions

---

canary/mqtt5/canary.ts

* sleep should use setTimeout not setInterval, leading to a memory/resource leak
* async and for-each don't work together.  While the program appeared to function as intended, all documentation (and IDE advice) seems to indicate this is not reliable as nothing is awaiting the top-level promise.

Fix some canary issues

---

MQTT5-UserGuide.md
lib/browser/aws_iot_mqtt5.ts
lib/browser/mqtt5.ts
lib/native/aws_iot_mqtt5.ts
lib/native/mqtt5.ts

Mqtt5 General Availability 

---

MQTT5-UserGuide.md
lib/browser/aws_iot.ts
lib/common/aws_iot_shared.ts
lib/native/aws_iot.ts

Documentation updates for custom auth connections

---

package-lock.json
package.json

Update axios to update follow-redirects

---

lib/browser/mqtt5.ts
lib/browser/mqtt5_utils.ts
package-lock.json
package.json
test/mqtt5.ts

Fix mqttjs5 compile error 

---

continuous-delivery/pack.sh

Bump pack size

---

lib/common/mqtt.spec.ts
lib/native/mqtt5.spec.ts
test/mqtt5.ts

* Update several MQTT will tests to be more forgiving of potential service race conditions
* Remove shared subscription distribution assertion because it's not valid

Attempt to reduce some test flakiness

---

continuous-delivery/pack.sh

Increase nodejs package size

---

.github/workflows/ci.yml
package-lock.json

- Windows 2019 will be fully unsupported by 2025-06-30, https://github.com/actions/runner-images/issues/12045. Remove it with msvc-15 and below.
- Use latest windows 2025 and msvc-17
- Latest submodules

remove windows-2019 and latest submodules
