- README.md
Brew formula for cmake uses 3.15.0 now.  cmake3 formula has been removed.
> fix missing cmake3 brew formula

- lib/browser/mqtt.ts
- lib/browser/trie.ts
Several trie traversals were using array indices and not entry values.
> Use correct keys in browser trie lookups

- continuous-delivery/build-binaries-linux-x64.yml
> Linux build does not need to install deps since it runs on the official node image

- .npmignore
- package-lock.json
- scripts/build.js
* Remove blanket ignore on test files to allow PQ test to be usable
* Disable building tests
https://github.com/awslabs/aws-crt-nodejs/issues/97
https://github.com/awslabs/aws-crt-nodejs/issues/80
> Test-related updates

- README.md
- package-lock.json
- package.json
- source/auth.c
- source/auth.h
- source/crypto.c
- source/crypto.h
- source/http_connection.c
- source/http_connection.h
- source/http_connection_manager.c
- source/http_connection_manager.h
- source/http_headers.c
- source/http_headers.h
- source/http_message.c
- source/http_message.h
- source/http_stream.c
- source/http_stream.h
- source/io.c
- source/io.h
- source/logger.c
- source/logger.h
- source/module.c
- source/module.h
- source/mqtt_client.c
- source/mqtt_client.h
- source/mqtt_client_connection.c
- source/mqtt_client_connection.h
- cmake-js moved from `devDependency `to regular `dependency`. You need it to build when a precompiled binary isn't available.
- It feels weird that this is a dependency for browser devs. I don't see another way with my limited understanding of npm. I'd love to see another example of a package with a C module that also works for browser...
- `#define NAPI_VERSION 4` before  `#include <node_api.h>`
- Docs say to do it this way: https://nodejs.org/api/n-api.html#n_api_usage
- Node 10.16 is required for NAPI_VERSION 4, update README
> Fix issues found when installing on Raspberry Pi

- lib/browser/http.ts
- lib/browser/mqtt.ts
- lib/common/event.ts
- package-lock.json
- samples/browser/http/index.ts
- samples/browser/http/package-lock.json
- samples/browser/pub_sub/package-lock.json
A grab bag of browser shim fixes:
* Update http sample to use new http interface
* Webpack error in http module
* Corked event args not unpacking properly leading to undefined arguments
* mqtt connect timeout default should be a reasonable value in milliseconds, not seconds
* activate http streams in browser http sample
* rework HttpClientConnection constructor to not be confusing and erroneously ambiguous with null/undefined parameters
* audit fix for vulnerable dependencies
> Browser fixes

- lib/common/mqtt.spec.ts
When the test failed, the done should be invoked as error. Or the error info will only be timeout.
Invoke done with error before return when error happens.
> invoke done with err

- lib/common/http.spec.ts
- source/http_headers.c
- When the string is larger than 256, the `napi_get_value_string_utf8` cannot fit into the buffer with the same capacity.
- make the capacity 1 byte larger than the length.
> fixed converting the headers

- .github/workflows/ci.yml
- lib/native/mqtt.ts
Ran the pub_sub sample to reproduce the leak mentioned in this issue with results that show garbage collection is now allowed to work: https://github.com/awslabs/aws-crt-nodejs/issues/149
```
[ogudavid@localhost:pub_sub(master)]$ node dist/index.js --endpoint xxxxxxxxxxxx.iot.us-west-2.amazonaws.com -r root.ca.pem -c certificate.pem.crt -k xxxxxxx-private.pem.key -t sdk/test/topic
The script uses approximately 4.69 MB
The script uses approximately 5.58 MB
The script uses approximately 6.41 MB
The script uses approximately 7.42 MB
The script uses approximately 8.21 MB
The script uses approximately 5.29 MB
The script uses approximately 6.34 MB
The script uses approximately 7.29 MB
The script uses approximately 8.34 MB
The script uses …
```
> Memory leak fix: releasing reference to payload and topic name

- lib/native/binding.d.ts
- lib/native/mqtt.ts
- source/module.h
- source/mqtt_client_connection.c
Bug was that `transform_websocket_args` pointer was being destroyed after 1st use, but pointer was re-used for any future reconnects, leading to access violoations. Solution is to create a new `transform_websocket_args` each time a transformation occurs.
Also moved a LOT of logic into the internal MQTT new() call, instead of the internal connect() call. I moved things that only needed to be set once (ex: websocket transform fn). I also added a bunch of cleanup calls to the finalize() function, seems like we were leaking JS resources before... but this is my first time really digging into this code so would love another set of eyeballs on this
> Fix crash on websocket reconnect.

- lib/browser/mqtt.ts
- lib/common/mqtt.spec.ts
- lib/common/mqtt.ts
- lib/native/binding.d.ts
- lib/native/mqtt.ts
- samples/browser/pub_sub/index.ts
In PR https://github.com/awslabs/aws-crt-nodejs/pull/172 I made an API-breaking change, switching the MQTT payload from ArrayBuffer to Uint8Array. I don't know what I was thinking. API breakage is bad. This puts it back the way it was (and fixes bugs where we weren't passing the correct type).
> Deliver MQTT payload as ArrayBuffer.

- lib/native/binding.d.ts
* Bindings Typescript has a new import that doesn't seem to work on clean builds of downstream consumers. Specifically observed in the aws-iot-device-sdk-js-v2 and complains that it cannot find the module. Using a relative import seems appropriate and the prior import in the same file shows that as well.
> Fixing import method of sibling CRT lib

- lib/browser/mqtt.ts
- lib/common/mqtt.spec.ts
- lib/common/mqtt.ts
- lib/native/binding.d.ts
- lib/native/mqtt.ts
- source/mqtt_client_connection.c
https://github.com/awslabs/aws-crt-nodejs/issues/171
- Accept any `ArrayBufferView` type (ex: `Uint8Array`). Previously we only accepted `DataView`.
- Fix bug in browser normalize_payload() that assumed a DataView was text.
- Add regression test that sends different payload types.
> Accept Uint8Array MQTT payloads

- lib/browser/mqtt.ts
- lib/common/mqtt.spec.ts
- lib/common/mqtt.ts
- lib/native/mqtt.ts
This fixes aws-iot-device-sdk-js-v2, which shouldn't have been using the `mqtt.Payload` type anyway. But the type-checks used to pass, and now they will again.
Anyway, it's cool to support ArrayBuffer as an outgoing data type. We already supported it under the hood.
> Add ArrayBuffer to supported MQTT payload types.

- builder.json
- samples/node/elasticurl/elasticurl.ts
- samples/node/elasticurl/package-lock.json
- source/auth.c
- source/http_connection.c
- source/http_connection_manager.c
- source/http_stream.c
- source/module.c
- source/module.h
- source/mqtt_client_connection.c
Probably related to issues that crash from an async callback, with stacktrace saying napi_call failed from callback. Since the env may exit before the async callback and fail all the napi_calls
- https://github.com/aws/aws-iot-device-sdk-js-v2/issues/96
The fix of previous issue leads to multiple underlying issues:
- We created an eventloop-group for node, but we never clean it up, so, we will actually result in some leak
- We are using event emitter to invoke the callback, which may lead to an asynced write operation, so, if we clean up the underlying resource right after the callback, we may crash. Instead, using the finalizer to clean up the resource.
Refering: https://nodejs.org/api/n-api.html#n_api_asynchronous_thread_safe_function_ca …
> fix the async call crash

- package-lock.json
- source/class_binder.h
- source/http_message.c
- source/mqtt_client_connection.c
- pubsub samples from iot-device-sdk-js-v2 exit with non-zero code
- on_publish callback is not cleaned up
- Release the C connection once the `close` called from node, instead of having the same life time with the node object to clean up the subscribe topic tree
- Bug fix: the hint of finalizer is not allocator.
> mqtt issue fix

- source/http_connection.c
when the proxy with authention, the connection to proxy will fail
found an coding issue to get wrong auth_method
> fix mqtt over websocket proxy authentication issue

- builder.json
- package-lock.json
* enable CI builds to fail on compiler warnings by default. Anticipating future default value change of this flag for non CI builds.
> Adding flag for CI builds to always treat compiler warnings as errors.

- source/io.c
* Updating aws-c-io for OverrideTrustStore log warning
> Updating aws-c-io for OverrideTrustStore log warning

- source/io.c
related:
https://github.com/awslabs/aws-c-common/pull/808
https://github.com/awslabs/aws-c-io/pull/386
> stop using deprecated aws_off_t

- package-lock.json
- package.json
> Temporarily revert cmake-js to 6.1 to unblock release

- CMakeLists.txt
Depends on:
* https://github.com/awslabs/aws-crt-nodejs/pull/248
> Split debug info out from node module

- package-lock.json
- package.json
- source/http_connection.c
- source/http_connection_manager.c
- source/http_stream.c
- source/module.c
- source/module.h
- source/mqtt_client_connection.c
* Add napi env checks to a number of native-to-node functions
* Error enum for nodejs crt
* Misc. memory cleanup for a few failure paths
> Add napi env checks where appropriate to native-to-node function calls

- lib/browser/ws.ts
- package-lock.json
- package.json
* Revert incorrect move from websocket-stream and replace with reference to forked, updated version
https://github.com/aws/aws-iot-device-sdk-js-v2/issues/206
> Update browser ws stream creation

- source/module.c
Better than hard crash.  We must figure out the right way to handle this eventually
https://github.com/awslabs/aws-crt-nodejs/issues/286
> Throw exception if the native addon init gets called more than once.

- continuous-delivery/pack.sh
A release just failed because we were 72 bytes over the cap.
Bump the cap up a smidge so we can release a security fix.
Long term, we should be doing these checks with each commit to main, not as something that fails at release time.
> bump up package size check

- .github/workflows/ci.yml
- .npmignore
- CMakeLists.txt
- builder.json
- continuous-delivery/build-binaries-linux-x64.yml
- continuous-delivery/build-binaries-unix.sh
- continuous-delivery/build-osx-x64-arm64.sh
- continuous-delivery/pack.sh
- continuous-delivery/pack.yml
- continuous-delivery/update-version.sh
- lib/native/binding.js
- scripts/build.js
- scripts/install.js
- source/io.c
**Issue:**
NPM package lacked arm64 binaries for macOS, so it didn't work as nicely on newer M1 Macs.
**Description of Changes:**
NPM package now includes arm64 binaries for macOS.
* Support cross-compiling on macOS, so any machine can make an x64 or arm64 binary.
* Can't just use an arm64 machine because we only have access to x64 macOS in our release pipeline.
* Decided against creating a single "universal" binary. It's a hassle to build (need to compile for both x64, then arm64, then glue them together with lipo) and would increase iteration time when developing on a Mac. And since our code [picks which binary to load](https://github.com/awslabs/aws-crt-nodejs/blob/12d30161dd8a3f78c0428caafe6ba1bd12b43288/lib/native/binding.js#L22), having distinct binaries seems simpler for now.
* A …
> Support for Apple M1

- lib/browser/aws_iot.ts
- lib/browser/mqtt.ts
- lib/common/aws_iot_shared.ts
- lib/native/aws_iot.ts
Modified MQTT connection builder to allow custom authorizer support. Added missing username and password options, and also added a function to make a default builder. All of these changes make MQTT connection builder closer to the Java V2 SDK in option parity, as well as adding custom authorizer support.
__________
> MQTT builder custom authorizer support

- lib/browser/mqtt.ts
* Variable-length reconnect (exponential backoff) was not working properly because the offline event only fires once, not each connection failure/disconnection.  To properly implement exponential backoff, we must use the close event, which fires every connection failure/disconnection.  We must also model additional connection state (desired, current) in order to properly react to the close event.
* The disconnect promise was not getting completed.  The mqtt-js disconnect implementation has many complexities most likely due to backwards compatibility contracts.  This update fixes this issue in a backwards compatible manner.
> Fix reconnect and disconnect behaviors in browser mqtt client wrapper

- package.json
- scripts/install.js
- Our pack stage of the release pipeline doesn't have Cmake, as it should not need to rebuild the native addon
- However the prepare script will always rebuild the native addon, which I doubt it's needed. At least for our release pipeline.
- Did a quick search about how people did for other nodejs lib with native addon. 
- Some use prepare to build, but they don't have install eg: [react-pdf](https://github.com/diegomura/react-pdf/blob/master/package.json). So that if people run [npm-pack](https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-pack) or publish, they will have the native addon available without install.
- Some use install to build, and the prepare just do the tsc thing. eg: [Couchbase](https://github.com/couchbase/couchnode/blob/master/package.json). …
> fix our release pipeline

- scripts/build.js
Fixes #354
Fixes `nativeSourceDir` not being globally defined, causing it to fail in functions outside of `main`.
__________
> Fix build script not having globally defined nativeSourceDir

- continuous-delivery/build-manylinux2014-aarch64-jenkins.sh
Nearly a year ago, aws-crt-builder changed the path where these docker images are uploaded to (see https://github.com/awslabs/aws-crt-builder/pull/153)
Use the newer path, instead of the old abandoned path
> Use newer docker image when creating releases

- continuous-delivery/build-manylinux2014-aarch64-jenkins.sh
**Issue:**
This docker image uses a newer version of git. When running with a bind mounted directory, git fails with "dubious ownership" errors.
Newer versions of git fail if the current user doesn't match the owner of the `.git/` folder. Since the directory is bind mounted, it is owned by the user on the host OS. But within a container, the user is `root` by default. Since `root` doesn't match the owner of the `.git/` folder, git fails.
**Description of changes:**
Set `--user` to match the owner of the bind mounted directory.
See the original diagnosis of the issue here: https://github.com/awslabs/aws-crt-python/pull/404
> Fix "dubious ownership" error from git, when running in docker using bind mounted directory

- continuous-delivery/build-manylinux2014-aarch64-jenkins.sh
**Issue:**
Release pipeline fails when running node in a docker image and *not* being the root user.
I'd previously made this change to fix any `git` calls we might make while running in the docker image, but turns out this task doesn't make any `git` calls
This reverts commit 380028fbf21e27fa735f02b460b882a41a52a424.
> Fix release pipeline

- .builder/actions/crt_size_check.py
**Resolves Issue:** https://github.com/awslabs/aws-crt-nodejs/issues/379
aws-lc v1.1.0 was generated a warning from some compilers, and aws-lc's CMakeLists always turns on warnings-as-errors.
**Description of Changes:**
Update to the latest release of aws-lc, which doesn't have the unused variable warning. Update all other submodules while we're at it.
```
aws-c-auth        v0.6.18 -> v0.6.21
aws-c-compression v0.2.15 -> v0.2.16
aws-c-http        v0.6.24 -> v0.6.28
aws-c-io          v0.13.7 -> v0.13.11
aws-c-sdkutils    v0.1.5 -> v0.1.7
aws-lc            v1.1.0 -> v1.3.0
s2n               v1.3.20 -> v1.3.29
```
> Update aws-lc to avoid build error.

- .builder/actions/crt_size_check.py
- .npmignore
- continuous-delivery/pack.sh
**Issue:**
The release pipeline failed due to the package size creeping up over our self-imposed limit
**Description of changes:**
* Bump limit from 14MiB -> 15MB
* Add note to size-check we do in CI, reminding users that there's also a release-time check.
* It sucks these checks aren't the same, but it would be a lot of work to check the TOTAL size in CI, which is an accumulation of every supported platform
> bump package size limit

- lib/native/aws_iot_mqtt5.spec.ts
This test was failing downstream builds from other repos which may or may not have credentials attached with sufficient permissions to use Iot Core.
> Switch mqtt5 websocket sigv4 test to use environmentally controlled credentials

- README.md
- lib/native/binding.d.ts
- lib/native/mqtt.spec.ts
- lib/native/mqtt.ts
- lib/native/mqtt5.spec.ts
- source/module.c
- source/mqtt_client_connection.c
- source/mqtt_client_connection.h
Adds operation statistics support to `aws-crt-nodejs` for MQTT311. Also adds operation statistics support tests for both MQTT311 and MQTT5 to increase code coverage and safety.
~~Relies on https://github.com/awslabs/aws-c-mqtt/pull/247 being merged and released.~~
__________
> Mqtt311 operation statistics support

- lib/browser/aws_iot.ts
- lib/browser/aws_iot_mqtt5.ts
- lib/browser/http.ts
- lib/browser/mqtt.ts
- lib/browser/mqtt5_utils.ts
- lib/browser/ws.ts
- lib/native/auth.ts
- lib/native/aws_iot.ts
- lib/native/http.ts
- lib/native/io.ts
- lib/native/mqtt.ts
- source/mqtt_client_connection.c
Fixes https://github.com/aws/aws-iot-device-sdk-js-v2/issues/93
Adjusts the Typescript code to check if arguments are `null` or `undefined` IF their properties or methods are being accessed and the argument is non-optional. While this should never occur, and we have checks in the C code to make sure the arguments are non-null, we have several cases where we take an argument, call something like `example.native_handle()` but do not check if `native_handle` is defined or not before doing so. For Typescript, this is not an issue because Typescript will not allow you to pass `null` or `undefined`, but the NodeJS CRT (and extension IoT SDK) are used by those with Javascript, which does not have this typing guarantee.
This can lead to customers …
> More usefull errors when missing data

- lib/common/mqtt.spec.ts
The shared MQTT311 tests are consistently flaky.  This PR is an attempt to uncover/resolve this flakiness.  After completing the refactor, I have not observed any test failures across a decent number of full CI re-runs.
This PR refactors the tests in several ways:
1. Try-blocks for all promise executor functions leading to rejections.  This keeps exceptions from disrupting anything outside the promise.
2. Drops all truthy resolution checks.  Awaiting the promise is sufficient.
3. Rewrites the tests to use a top-down procedural style for clarity of ordering.  Step-by-step awaits are not how you'd write a real application, but for tests, they make following the control flow and expectations much easier.
By submitting this pull request, I confirm that my contribution is made under the terms …
> Refactor flaky MQTT311 tests

- lib/browser.ts
- lib/common/cancel.spec.ts
- lib/common/cancel.ts
- lib/common/promise.spec.ts
- lib/common/promise.ts
- lib/index.ts
- lib/native/eventstream.spec.ts
- lib/native/eventstream.ts
A bunch of miscellaneous CRT updates to support eventstream and Greengrass RPC.
* Some events have been renamed
* Added support for LiftedPromise, a promise whose resolve and reject methods are available to external actors.  Primary use is to remove internal awaits in the promise body that may never resolve (based on network events, for example) and instead let  external events drive resolution/rejection
* Added support for CancelController, a simple type with a cancel method that can be listened to for promise rejection
> Eventstream client integration

- .builder/actions/crt-ci-test.py
- MQTT5-UserGuide.md
- lib/native/aws_iot.spec.ts
- lib/native/aws_iot.ts
- lib/native/aws_iot_mqtt5.spec.ts
- lib/native/aws_iot_mqtt5.ts
- lib/native/io.ts
- test/mqtt5.ts
Adds PKCS12 support to the MQTT311 and MQTT5 builders. Also adds PKCS11 and PKCS12 documentation to the MQTT5 user guide.
_________
> PKCS12 builder support

- source/module.c
Revert the changes that prevented multi-init of the NAPI module and add ref-counting support and careful, matching shutdown when the last ref goes away.
https://github.com/aws/aws-iot-device-sdk-js-v2/discussions/360
A more complex solution might consider making elg/hr/bootstrap a per-environment set of data, but for now, the simplest approach with the least possibility of error is to simply have all environments reference a shared triple and use ref-counting to drop the triple once no env-users remain.
> Let's try ref counting

- lib/native/aws_iot.ts
- lib/native/mqtt.spec.ts
- lib/native/mqtt.ts
- source/mqtt_client_connection.c
~Adjusts MQTT311's disconnect behavior to not always free the native resources when `disconnect()` is called, instead adding a new option (`close_on_disconnect`) that can be set to `false`, allowing for manual reconnects. Also exposes the `close()` function so the connection can be cleaned manually if `close_on_disconnect` is set to `false`.~
~Also fixes a number of segfaults that can occur if the MQTT311 connection is closed. Now errors are thrown explaining that the MQTT311 connection has been closed and is no longer usable, rather than segfaulting.~
~Adding documentation for these new functions and tests to ensure functionality works as expected by default, and with the new option.~
Fixes segfaults that occur when you call `connect`, `disconnect`, and then …
> Adjust MQTT311 disconnect cleanup

- lib/browser/mqtt.ts
- lib/native/mqtt.ts
Adds conditions to make sure the input data types passed in the main MQTT311 operations (publish, subscribe, unsubscribe) are the correct data types and, if they are not, returns an error stating the issue. While this is done automatically and not needed for Typescript, for pure Javascript it can be easy to accidentally pass the wrong type and, when this happens, the error returned doesn't make it completely clear what is going on. This PR makes it where if an incorrect datatype is passed, a rejected promise is returned.
____________
> Validate the input types in the main operations in MQTT311

- lib/native/eventstream.ts
> Remove developer preview disclaimer on eventstream

- canary/mqtt5/canary.ts
- canary/mqtt5/package.json
- codebuild/CanaryWrapper.py
- codebuild/CanaryWrapper_Classes.py
- codebuild/CanaryWrapper_MetricFunctions.py
- codebuild/mqtt5-nodejs-canary-test.yml
> Setup Short Run Mqtt5 Canary

- source/module.c
This reverts commit 0aa0feb63859b8f1f6bca1759249df1d74c15ef2.
The enum `napi_no_external_buffers_allowed` is introduced in node21 and backport to node 14.21.2, 16.19.0, 18.13.0.
(Details in : https://github.com/nodejs/node/pull/45181)
We hardcoded `napi_no_external_buffers_allowed` value until we upgrade to node21. 
> Hardcoded `napi_no_external_buffers_allowed` value for Node 21 and below

- docsrc/typedoc-browser.json
- docsrc/typedoc-node.json
- lib/browser/aws_iot.ts
- lib/browser/aws_iot_mqtt5.ts
- lib/native/aws_iot.ts
- lib/native/aws_iot_mqtt5.ts
- lib/native/mqtt.ts
- package-lock.json
- package.json
- npm update to address Dependabot warnings about "axios" and "follow-redirects"
- this broke the docs, so update typedoc to latest version support Node 14.x, and fix new warnings
> NPM update to resolve dependabot warnings

- package-lock.json
- package.json
https://github.com/awslabs/aws-crt-nodejs/issues/534
Update axios to version 1.6.7 because of security vulnerability: https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788 
> update axios version

- MQTT5-UserGuide.md
> Add windows cert section to mqtt5 user guide

- builder.json
macos job currently fails in CI.
Prior to Node v16, Mac OS arm64 has only experimental support (for example, see [Node v15 docs](https://github.com/nodejs/node/blob/v15.x/BUILDING.md#platform-list)). So, using node-16 for Mac OS arm64 job seems the right solution.
> Use node-16 for Mac OS arm64

- CMakeLists.txt
This PR is the same as https://github.com/awslabs/aws-crt-cpp/pull/648
At configuration time, `s2n-tls` performs a number of feature probes against libcrypto in order to configure itself. In the current implementation of aws-crt-nodejs build system, the correct libcrypto does not yet exist (nor are aws-lc's headers visible to the feature check, for that matter). This results in a misconfigured s2n-tls.
Unfortunately, there is no easy way to change s2n-tls to be configured at build time, because CMake standard functionality for this (`try_compile` function) can be used only at configuration time.
Build and install aws-lc into a build directory at configuration time, so libcrypto can be used by `s2n-tls`.
This PR depends on …
> Prebuild aws-lc

- continuous-delivery/pack.yml
- continuous-delivery/publish.yml
- continuous-delivery/test-version-exists.yml
Bump the install phase nodejs version from 10 to 14 in continuous-delivery related yml files.
CD is currently failing at the POST_BUILD phase of the aws-crt-nodejs-cd-combine-binaries CodeBuild Build Project with the context "COMMAND_EXECUTION_ERROR: Error while executing command: bash ./continuous-delivery/pack.sh. Reason: exit status 1" 
logs indicate:
npx tsc -p tsconfig.json
Unexpected token ?
run(`npx tsc -p tsconfig.json`) is in the `scripts/tsc.js`
Which is listed in the "prepare": "node ./scripts/tsc.js && node ./scripts/install.js" of the package.json.
The related yml file for pack sets the runtime-version of nodejs to 10. Changing this to our minimum supported version of 14 should resolve the issue. We may as well also bump the version from 10 -> 14 in the publish and …
> Continuous Delivery nodejs version bump

- .builder/actions/crt_size_check.py
- CMakeLists.txt
- scripts/build_dependencies/build_step_cmake.js
- source/io.c
- Prebuild S2N and update submodule for using s2n_cleanup_thread()
> Prebuild S2N

- continuous-delivery/pack.sh
- Release pipeline is failing with 
```
echo 'Current package size: 25736'
Current package size: 25736
+ expr 25736 '>' 25000
```
> bump pack size

- .github/workflows/ci.yml
- .github/workflows/docs.yml
> Switch CI to Roles

- source/http_connection.c
- source/http_connection_manager.c
- source/http_message.c
- source/http_stream.c
**Issue:** (internal ticket V1637484435)
When doing SigV4A signing from aws-sdk-js-v3, memory usage gradually increases due to memory leaks.
**Description of changes:**
Fix leak that occurred if headers were queried repeatedly.
**Future Work:**
All native unit tests should check that they aren't leaking memory. I spent a few hours trying to add such tests, but couldn't get it working in a reliable way. I didn't want this to hold back the fix, so leaving it for another day. See these blog posts for hints on various techniques NodeJS has used for leak testing through the years: https://joyeecheung.github.io/blog/2024/03/17/memory-leak-testing-v8-node-js-1/, https://joyeecheung.github.io/blog/2024/03/17/memory-leak-testing-v8-node-js-2/
By submitting this pull request, I confirm that my …
> Fix memory leak during signing

- .builder/actions/crt_size_check.py
- .github/workflows/ci.yml
```
aws-c-auth         v0.8.0 -> v0.8.3
aws-c-cal          v0.8.0 -> v0.8.1
aws-c-common       v0.10.3 -> v0.10.9
aws-c-compression  v0.3.0 ✓
aws-c-event-stream v0.5.0 ✓
aws-c-http         v0.9.2 ✓
aws-c-io           v0.15.3 ✓
aws-c-mqtt         v0.11.0 ✓
aws-c-sdkutils     v0.2.0 -> v0.2.2
aws-checksums      v0.2.0 -> v0.2.2
aws-lc             v1.37.0 -> v1.43.0
s2n                v1.5.5 -> v1.5.11
```
- Major changes we pull in from submodules:
- https://github.com/awslabs/aws-c-common/pull/1185 -- fix heap overflow on uri parsing
- https://github.com/awslabs/aws-c-common/pull/1182 -- Fix CRC64NVME crash on machines with disabled AVX
- https://github.com/awslabs/aws-c-auth/pull/261
By submitting this pull request, I confirm that my …
> Fix segfaults -- CRC64NVME on machines with disabled AVX and uri parsing corner case.

- lib/browser/mqtt_request_response.ts
- lib/common/mqtt_request_response.ts
- source/mqtt_request_response.c
- test/mqtt_request_response.ts
Issue #, if available:
Service client might need a topic where a stream's publish message was received.
Description of changes:
Add a topic argument to incoming publish callback.
**NOTE**: In this PR, I put topic before payload, similarly to request client.
> Add topic argument to publish callback in request-response stream client

- .github/workflows/ci.yml
We rely on qemu to test aarch64 on x86-64 github runners.
Qemu had a bug where they had a bug with incorrectly mapping address space. That mostly worked fine until kernel patch that increased entropy in their address randomization. TLDR; qemu likes to segfault a lot against new kernels on our aarch64 test. Solution is to switch to a different github qemu user static image that forces a latest version of qemu, that has the bug fixed.
if you want to read more - https://github.com/tonistiigi/binfmt/issues/240
> fix nodejs arm ci

- .github/workflows/ci.yml
- builder.json
- source/mqtt_request_response.c
windows-vc14-x86 was reporting a conversion from `size_t` to `uint32_t` with a possible loss of data when used with `napi_get_element`. 
In CI, we previously ran `npm install` before `node scripts/build.js -DAWS_WARNINGS_ARE_ERRORS=ON`. So that the first step actually build the shared lib without warning as errors and the next step just picked the cached built artifacts instead of building the source code with warning as errors, which hide the warnings generated by compiler.
Move the build with warnings as errors before npm install to make sure it reports warnings as error correctly.
> Build with Warning as Error

- source/mqtt_request_response.c
The upstream PR https://github.com/awslabs/aws-c-mqtt/pull/389 changes API for the request-response operations. Because of that, we cannot release aws-c-mqtt, otherwise it might block other releases needed for other tasks. So, the purpose of this PR is just to unblock release of aws-c-mqtt breaking changes. Support for the new fields in request-response operations will be implemented in the future.
Adjust signature of the incoming publish callback for the request response operations.
> Support changes in req-resp operations

- codebuild/macos_compatibility_check.py
- package-lock.json
- package.json
- scripts/build_dependencies/build_step_cmake.js
Fixes https://github.com/awslabs/aws-crt-nodejs/pull/614. Dependabot is updating both axios and jest-puppeteer because jest-puppeteer also has axios as a dependency and older jest-puppeteer has older version of axios. We tried to update jest-puppeteer but that results in a bunch of breaking changes, see: https://github.com/awslabs/aws-crt-nodejs/pull/616. For now, let's just update axios and override it so that we use the latest version of axios everywhere. We can bump jest-puppeteer to latest version later.
```
❯ npm audit
found 0 vulnerabilities
```
> Bump Axios to Fix Velnerabilities + Bump Minimum MacOS version to 10.15

- package-lock.json
https://github.com/awslabs/aws-crt-nodejs/pull/621
- run `npm audit fix` and then `npm install --lockfile-version=1`
> Bump tar-fs from 2.1.2 to 2.1.3
